### ISSUE TITLE
pressing backslash to open chat and pressing space crashes the game [1.19.2]

### ISSUE THREAD

**Issue by Sea-Pickle** [maxuser0/minescript#1]
mods:
appleskin-forge-mc1.19-2.4.2.jar
architectury-6.2.46-forge.jar
balm-4.5.3.jar
clienttweaks-forge-1.19-8.1.0.jar
cloth-config-8.2.88-forge.jar
entityculling-forge-1.5.2-mc1.19.1.jar
forgeautofish-5.0.2-1.19.jar
HealthOverlay-1.19.2-7.1.1.jar
InventorySorter-1.8.10-1.19.jar
Jade-1.19.1-forge-8.3.0.jar
light-overlay-7.0.1-forge.jar
Mantle-1.18.2-1.9.27.jar.disabled (disabled)
minescript-mc1.19.2-forge-mod-2.1.jar
MouseTweaks-forge-mc1.19-2.23.jar
OptiFine_1.19.2_HD_U_H9.jar
RoughlyEnoughItems-9.1.550.jar
Xaeros_Minimap_22.14.1_Forge_1.19.1.jar
XaerosWorldMap_1.27.0_Forge_1.19.1.jar

crash logs:

[crash-2022-11-22_18.54.31-client.txt](https://github.com/maxuser0/minescript/files/10072260/crash-2022-11-22_18.54.31-client.txt)
[crash-2022-11-01_20.22.53-fml.txt](https://github.com/maxuser0/minescript/files/10072261/crash-2022-11-01_20.22.53-fml.txt)

steps to reproduce:
1.press "\" to open chat
2.press space
3.game freezes, then crashes

**Comment by maxuser0** [comment]
Fixed on main branch for fabric mod:

[commit 86a19b70d7bb3a920e10b4c899113dc72ea0e0c9](https://github.com/maxuser0/minescript/commit/86a19b70d7bb3a920e10b4c899113dc72ea0e0c9)

and synced to forge mod:

[commit 785aaab1cfee85384a7ff853c84b1d7244c95f7a
](https://github.com/maxuser0/minescript/commit/785aaab1cfee85384a7ff853c84b1d7244c95f7a)

Planning to release this with Minescript v2.2 in the coming days.

Thanks for the crash report!
