### ISSUE TITLE
block_pack.block_bounds() returns invalid values if there is no block in the area 

### ISSUE THREAD

**Issue by sametcetinkaya1447** [maxuser0/minescript#11]
example code: 
`
import minescript as ms

p_x, p_y, p_z = [int(i) for i in ms.player_position()]
scan_radius = 5

pos1 = (p_x - scan_radius, p_y, p_z - scan_radius)
pos2 = (p_x + scan_radius, p_y + 10, p_z + scan_radius)
min_pos, max_pos = block_pack.block_bounds()

print(min_pos, max_pos)
`

**Comment by maxuser0** [comment]
Fixed in 2152b7ceed2a7f1d283850bfac4724f6a5656619, to be released in 4.0-beta2.
